#!/usr/bin/env python3
"""Sweep Escalated/Failed Notion rows and reset retry-able ones to ReadyToApply.

Classifies each role by its latest escalation reason (from partial-submission-log.json
and the most recent diagnostics metadata). Skips reasons in the auto-skip list from
apply-intelligence.json, captcha-related blocks, and other unresolvable conditions.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from auto_apply import resolve_role_dir  # noqa: E402

# apply-intelligence.json is optional (generated by retrospective.py); a
# missing or invalid file just disables the auto-skip list.
_INTEL_PATH = ROOT / "data" / "apply-intelligence.json"
try:
    INTEL = json.loads(_INTEL_PATH.read_text())
except (FileNotFoundError, json.JSONDecodeError):
    INTEL = {}
AUTO_SKIP_REASONS = {
    k for k, v in INTEL.get("escalation_playbooks", {}).items()
    if v.get("action") == "skip"
}

SKIP_PATTERNS = [
    re.compile(r".*captcha.*", re.I),
    re.compile(r".*spam.*", re.I),
    re.compile(r".*video[-_].*", re.I),
    re.compile(r"needs_human"),
    re.compile(r".*workday-account-creation.*"),
    re.compile(r".*workday-multi-page-wizard.*"),
    re.compile(r".*workday-job-not-found.*"),
    re.compile(r".*workday-form-shape-unknown.*"),
    re.compile(r".*workday-signin-failed.*"),
    re.compile(r".*workday-account-required.*"),
    re.compile(r".*linkedin-no-longer-accepting.*"),
    re.compile(r"not-automatable-host[-:].*"),
    re.compile(r".*expired.*", re.I),
    re.compile(r".*page-not-loaded.*"),
    re.compile(r".*page-load-failure.*"),
    re.compile(r"modal-did-not-open"),
    re.compile(r".*404.*"),
]

RETRY_HINTS = [
    "essay", "extra-required-fields", "long_form", "generate_cover_letter",
    "cover-letter", "low_confidence", "radio_value_unmatched",
    "compute_salary", "additional-page-not-advancing", "unknown-page",
    "unknown_field", "unknown-ats", "lever-", "ashby-extra",
    "modal_closed_unexpectedly", "subagent-no-output",
    "no-apply-action-found", "max-pages-exceeded",
    "greenhouse-required-fields-unfilled", "greenhouse-confirmation-not-detected",
    "greenhouse-form-not-detected", "greenhouse-email-verification-required",
    "ashby-confirmation-not-detected", "ashby-form-not-detected",
    "smartrecruiters-form-not-detected", "teamtailor-form-not-detected",
    "jobvite-form-not-detected", "no-continue-on-top-choice",
    "no-continue-button-on-contact",
]


def latest_diagnostic_reason(role_dir: Path) -> str | None:
    diag_root = role_dir / "diagnostics"
    if not diag_root.is_dir():
        return None
    runs = sorted(diag_root.glob("*"), reverse=True)
    if not runs:
        return None
    md = next(runs[0].glob("*.metadata.json"), None)
    if not md:
        return None
    try:
        data = json.loads(md.read_text())
        return data.get("reason") or data.get("metadata", {}).get("result", {}).get("reason")
    except Exception:
        return None


def latest_partial_reason(role_dir: Path) -> str | None:
    psl = role_dir / "partial-submission-log.json"
    if not psl.is_file():
        return None
    try:
        d = json.loads(psl.read_text())
        return d.get("halt_reason")
    except Exception:
        return None


def manual_apply_reason(role_dir: Path) -> str | None:
    f = role_dir / "MANUAL-APPLY.md"
    if not f.is_file():
        return None
    m = re.search(r"Escalation reason:\*\*\s*`([^`]+)`", f.read_text())
    return m.group(1) if m else None


def classify(reason: str | None) -> tuple[str, str]:
    if not reason:
        return ("unknown", "no-reason-found")
    if reason in AUTO_SKIP_REASONS:
        return ("skip", f"auto-skip:{reason}")
    for p in SKIP_PATTERNS:
        if p.search(reason):
            return ("skip", f"pattern-skip:{reason}")
    for hint in RETRY_HINTS:
        if hint in reason:
            return ("retry", f"retry-hint:{reason}")
    return ("unknown", f"unrecognised:{reason}")


def list_queue(status: str) -> list[dict]:
    out = subprocess.run(
        ["python", "scripts/auto_apply.py", "list-queue", "--status", status],
        capture_output=True, text=True, check=True, cwd=ROOT,
    )
    return json.loads(out.stdout)


def mark_ready(page_id: str) -> bool:
    r = subprocess.run(
        ["python", "scripts/notion_cli.py", "update-status", page_id, "ReadyToApply"],
        capture_output=True, text=True, cwd=ROOT,
    )
    return r.returncode == 0


def main(execute: bool):
    rows = []
    for status in ("Escalated", "Failed"):
        for row in list_queue(status):
            rid = row["id"]
            try:
                role_dir = resolve_role_dir(rid)
            except Exception:
                rows.append((status, rid, row.get("company"), row.get("title"), None, "skip", "no-folder", row["page_id"]))
                continue
            reason = (
                latest_diagnostic_reason(role_dir)
                or latest_partial_reason(role_dir)
                or manual_apply_reason(role_dir)
            )
            verdict, detail = classify(reason)
            rows.append((status, rid, row.get("company"), row.get("title"), reason, verdict, detail, row["page_id"]))

    # tally
    from collections import Counter
    tally = Counter((r[5], r[6].split(":", 1)[0]) for r in rows)
    print("Classification tally:")
    for k, n in tally.most_common():
        print(f"  {k[0]:8s} {k[1]:15s}  {n}")
    print()

    retries = [r for r in rows if r[5] == "retry"]
    print(f"Retry candidates: {len(retries)}")
    by_reason = Counter(r[4] for r in retries)
    for reason, n in by_reason.most_common(40):
        print(f"  {n:4d}  {reason}")

    unknowns = [r for r in rows if r[5] == "unknown"]
    print(f"\nUnknown reasons: {len(unknowns)}")
    by_unknown = Counter(r[4] for r in unknowns)
    for reason, n in by_unknown.most_common(40):
        print(f"  {n:4d}  {reason}")

    if not execute:
        print("\nDry-run: pass --execute to update Notion.")
        return

    print("\nExecuting…")
    ok = 0
    fail = 0
    for r in retries:
        if mark_ready(r[7]):
            ok += 1
        else:
            fail += 1
    print(f"Marked ReadyToApply: ok={ok} fail={fail}")


if __name__ == "__main__":
    main(execute="--execute" in sys.argv)
